<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<?php 
$_order = $block->getOrderItemsDetails(); 
$shipping_addresses = $_order->getShippingAddress()->getData();
$billing_addresses = $_order->getBillingAddress()->getData();
?>
<div class="container">
    <div class="checkout-success">
    <h3>รายละเอียดการสั่งซื้อ <small>กรุณาตรวจสอบข้อมูลการสั่งซื่อของท่าน</small></h3>
    
    <?php if ($block->getOrderId()):?>
        <?php if ($block->getCanViewOrder()) :?>
            <h5><?php echo __('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></h5>
        <?php  else :?>
            <h5><?php echo __('Your order # is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></h5>
        <?php endif;?>
            <p><?php /* @escapeNotVerified echo __('We\'ll email you an order confirmation with details and tracking info.')  */?> ท่านสามารถตรวจสอบรายละเอียดการยืนยันสั่งซื้อสินค้าและรายละเอียดการจัดส่งสินค้าได้จากอีเมลสั่งซื้อของท่าน</p>
    <?php endif;?>
    <?php echo $block->getAdditionalInfoHtml() ?>
<table>
    <tr><td><h4>ข้อมูลจัดส่งสินค้า</h4></td></tr>
    <tr>
        <td>
            <table>
            <!-- <tr><td>Shipping Address</td><td><?php print_r($shipping_addresses ); ?></td></tr> -->
            <tr><td>ที่อยู่จัดส่งสืนค้า</td></tr>
            <tr><td>ชื่อ-สกุล</td><td><?php echo $shipping_addresses["firstname"]." ".$shipping_addresses["lastname"]; ?></td></tr>
          <!--   <tr><td>Lastname</td><td><?php echo $shipping_addresses["lastname"]; ?></td></tr> -->
            <tr><td>อีเมล</td><td><?php echo $shipping_addresses["email"]; ?></td></tr>
            <tr><td>เบอร์โทรศัพท์</td><td><?php echo $shipping_addresses["telephone"]; ?></td></tr>
            <tr><td>ที่อยู่</td><td><?php echo $shipping_addresses["street"].", ". $shipping_addresses["city"]." รหัสไปรษณีย์". $shipping_addresses["postcode"]; ?></td></tr>
            </table>
        </td>
        <td>
            <table>
            <!--   <tr><td>Billing Address</td><td><?php print_r($billing_addresses); ?></td></tr> -->
            <tr><td>ที่อยู่กำกับภาษี</td></tr>
            <tr><td>ชื่อ-สกุล</td><td><?php echo $billing_addresses["firstname"]." ".$billing_addresses["lastname"]; ?></td></tr>
           <!--  <tr><td>Lastname</td><td><?php echo $billing_addresses["lastname"]; ?></td></tr> -->
            <tr><td>อีเมล</td><td><?php echo $billing_addresses["email"]; ?></td></tr>
            <tr><td>เบอร์โทรศัพท์</td><td><?php echo $billing_addresses["telephone"]; ?></td></tr>
            <tr><td>ที่อยู่</td><td><?php echo $billing_addresses["street"].", ". $billing_addresses["city"].", รหัสไปรษณีย์ ". $billing_addresses["postcode"]; ?></td></tr>
            </table>
        </td>
    </tr>
   <!--  <tr><td>Sub Total</td><td><?php echo $_order->formatPrice($_order->getSubTotal()); ?></td> -->
   
</table>
<table>
    <tbody>
    <tr>
        <th>SKU</th>
        <th>ชื่อสินค้า</th>
        <th>จำนวน</th>
        <th>ราคา</th>
    </tr>
<?php
$orderAllVisibleItems = $_order->getAllVisibleItems();
foreach($orderAllVisibleItems as $_item ) {
    //print_r($_item->getData());
   $orders_item = $_item->getData();
  // var_dump($orders_item);
// $orderid = $block->getOrderId();
// echo $orderid;
?>
<tr>
    <td><?php  echo $orders_item['sku']; ?></td>
    <td><?php  echo $orders_item['name']; ?></td>
    <td><?php  echo $orders_item['qty_ordered'];?></td>
    <td><?php  echo $orders_item['row_total'];  }?></td>
</tr>
<tr><td>การจัดส่ง</td><td><?php echo "จัดส่งฟรี (". $_order->formatPrice($_order->getShippingAmount()).")"; ?></td>
<tr><td>ราคารวมสุทธิ</td><td><?php echo $_order->formatPrice($_order->getGrandTotal())." "; ?></td></tr>

</tbody>
</table>

<div class="info-payment">
 <div style="border-top:1px #cccccc solid;border-bottom:1px #cccccc solid;padding:10px 0">
                    <table class="bank-sec" width="100%" cellspacing="0" cellpadding="0">
                        <tbody>
                            <tr><td colspan="5" height="25" align="center"><b>สำหรับวิธีโอนเงินผ่านธนาคาร</b> </td></tr>
                            <tr style="font-size:15px"><td style="padding:3px 0"><img src="https://test2.babykidsbestbuyonline.com/pub/media/wysiwyg/THbank/THbank_logo1.png" width="25" height="25" class="CToWUd"></td>
                            <td>ธนาคารกสิกรไทย</td>
                          <td>บจก.เอซ-คอน ดิจิทัล (ไทยแลนด์)</td>
                            <td>บัญชีเลขที่</td>
                            <td><p>034-8-33247-3</p></td>
                            </tr>
                            <tr style="font-size:15px">
                            <td style="padding:3px 0"><img src="https://test2.babykidsbestbuyonline.com/pub/media/wysiwyg/THbank/THbank_logo2.png" width="25" height="25" class="CToWUd"></td>
                            <td>ธนาคารกรุงเทพ</td>
                         <td>บจก.เอซ-คอน ดิจิทัล (ไทยแลนด์)</td>
                            <td>บัญชีเลขที่</td>
                            <td><p>177-0-82170-8</p></td>
                            </tr>
                            <tr style="font-size:15px">
                            <td style="padding:3px 0"><img src="https://test2.babykidsbestbuyonline.com/pub/media/wysiwyg/THbank/THbank_logo3.png" width="25" height="25" class="CToWUd"></td>
                            <td>ธนาคารไทยพาณิชย์</td>
                           <td>บจก.เอซ-คอน ดิจิทัล (ไทยแลนด์)</td>
                            <td>บัญชีเลขที่</td>
                            <td><p>047-2-60961-8</p></td>
                            </tr>
                            <tr style="font-size:15px">
                            <td style="padding:3px 0"><img src="https://test2.babykidsbestbuyonline.com/pub/media/wysiwyg/THbank/THbank_logo4.png" width="25" height="25" class="CToWUd"></td>
                            <td>ธนาคารกรุงไทย</td>
                    <td>บจก.เอซ-คอน ดิจิทัล (ไทยแลนด์)</td>
                            <td>บัญชีเลขที่</td>
                            <td><p>011-0-21901-5</p></td>
                            </tr>
                            <tr style="font-size:15px">
                            <td style="padding:3px 0"><img src="https://test2.babykidsbestbuyonline.com/pub/media/wysiwyg/THbank/THbank_logo5.png" width="25" height="25" class="CToWUd"></td>
                            <td>ธนาคารทหารไทย</td>
                        <td>บจก.เอซ-คอน ดิจิทัล (ไทยแลนด์)</td>
                            <td>บัญชีเลขที่</td>
                            <td><p>001-9-47849-4</p></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
</div>
<br/>
    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
        </div>
    </div>
</div>

</div>